# Generated by Django 4.0.4 on 2022-05-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('bike_name', models.CharField(max_length=100)),
                ('year_manufa', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(null=True)),
                ('kilometers', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
